version: "3"
services :
  discovery-service:
    build: ./discovery-service
    container_name: discovery-container
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 3
    restart: unless-stopped

  config-service:
    build: ./config-service
    container_name: config-container
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 3
    depends_on:
      discovery-service:
        condition: service_healthy
    restart: unless-stopped

  customer-service:
    build: ./customer-service
    container_name: customer-container
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
    restart: unless-stopped

  account-service:
    build: ./account-service
    container_name: account-container
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 3
    depends_on:
      customer-service:
        condition: service_healthy
    restart: unless-stopped

  gateway-service:
    build: ./gateway-service
    container_name: gateway-container
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 3
    depends_on:
      config-service:
        condition: service_healthy
    restart: unless-stopped